package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nDeviceKey", "nGroupKey", "nGroupMask", "bActionTimeEnable", "nActionTime", "pBroadcastAddress", "nTimeOut", "nReserved"})
public class MV_ACTION_CMD_INFO extends Structure {
	/** \u8bbe\u5907\u5bc6\u94a5 */
	public int nDeviceKey;
	/** \u7ec4\u952e */
	public int nGroupKey;
	/** \u7ec4\u63a9\u7801 */
	public int nGroupMask;
	/** \u53ea\u6709\u8bbe\u7f6e\u62101\u65f6Action Time\u624d\u6709\u6548\uff0c\u975e1\u65f6\u65e0\u6548 */
	public int bActionTimeEnable;
	/** \u9884\u5b9a\u7684\u65f6\u95f4\uff0c\u548c\u4e3b\u9891\u6709\u5173 */
	public long nActionTime;
	/**
	 * \u5e7f\u64ad\u5305\u5730\u5740<br>
	 * C type : const char*
	 */
	public Pointer pBroadcastAddress;
	/** \u7b49\u5f85ACK\u7684\u8d85\u65f6\u65f6\u95f4\uff0c\u5982\u679c\u4e3a0\u8868\u793a\u4e0d\u9700\u8981ACK */
	public int nTimeOut;
	/**
	 * \u9884\u7559 | en:Reserved<br>
	 * C type : unsigned int[16]
	 */
	public int[] nReserved = new int[16];
	public MV_ACTION_CMD_INFO() {
		super();
	}
	/**
	 * @param nDeviceKey \u8bbe\u5907\u5bc6\u94a5<br>
	 * @param nGroupKey \u7ec4\u952e<br>
	 * @param nGroupMask \u7ec4\u63a9\u7801<br>
	 * @param bActionTimeEnable \u53ea\u6709\u8bbe\u7f6e\u62101\u65f6Action Time\u624d\u6709\u6548\uff0c\u975e1\u65f6\u65e0\u6548<br>
	 * @param nActionTime \u9884\u5b9a\u7684\u65f6\u95f4\uff0c\u548c\u4e3b\u9891\u6709\u5173<br>
	 * @param pBroadcastAddress \u5e7f\u64ad\u5305\u5730\u5740<br>
	 * C type : const char*<br>
	 * @param nTimeOut \u7b49\u5f85ACK\u7684\u8d85\u65f6\u65f6\u95f4\uff0c\u5982\u679c\u4e3a0\u8868\u793a\u4e0d\u9700\u8981ACK<br>
	 * @param nReserved \u9884\u7559 | en:Reserved<br>
	 * C type : unsigned int[16]
	 */
	public MV_ACTION_CMD_INFO(int nDeviceKey, int nGroupKey, int nGroupMask, int bActionTimeEnable, long nActionTime, Pointer pBroadcastAddress, int nTimeOut, int nReserved[]) {
		super();
		this.nDeviceKey = nDeviceKey;
		this.nGroupKey = nGroupKey;
		this.nGroupMask = nGroupMask;
		this.bActionTimeEnable = bActionTimeEnable;
		this.nActionTime = nActionTime;
		this.pBroadcastAddress = pBroadcastAddress;
		this.nTimeOut = nTimeOut;
		if ((nReserved.length != this.nReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.nReserved = nReserved;
	}
	public MV_ACTION_CMD_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_ACTION_CMD_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_ACTION_CMD_INFO implements Structure.ByValue {
		
	};
}
