package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nType", "pInfo", "nInfoSize"})
public class MV_ALL_MATCH_INFO extends Structure {
	/** ch:\u9700\u8981\u8f93\u51fa\u7684\u4fe1\u606f\u7c7b\u578b\uff0ce.g. MV_MATCH_TYPE_NET_DETECT | en:Information type need to output ,e.g. MV_MATCH_TYPE_NET_DETECT */
	public int nType;
	/**
	 * ch:\u8f93\u51fa\u7684\u4fe1\u606f\u7f13\u5b58\uff0c\u7531\u8c03\u7528\u8005\u5206\u914d | en:Output information cache, which is allocated by the caller<br>
	 * C type : void*
	 */
	public Pointer pInfo;
	/** ch:\u4fe1\u606f\u7f13\u5b58\u7684\u5927\u5c0f | en:Information cache size */
	public int nInfoSize;
	public MV_ALL_MATCH_INFO() {
		super();
	}
	/**
	 * @param nType ch:\u9700\u8981\u8f93\u51fa\u7684\u4fe1\u606f\u7c7b\u578b\uff0ce.g. MV_MATCH_TYPE_NET_DETECT | en:Information type need to output ,e.g. MV_MATCH_TYPE_NET_DETECT<br>
	 * @param pInfo ch:\u8f93\u51fa\u7684\u4fe1\u606f\u7f13\u5b58\uff0c\u7531\u8c03\u7528\u8005\u5206\u914d | en:Output information cache, which is allocated by the caller<br>
	 * C type : void*<br>
	 * @param nInfoSize ch:\u4fe1\u606f\u7f13\u5b58\u7684\u5927\u5c0f | en:Information cache size
	 */
	public MV_ALL_MATCH_INFO(int nType, Pointer pInfo, int nInfoSize) {
		super();
		this.nType = nType;
		this.pInfo = pInfo;
		this.nInfoSize = nInfoSize;
	}
	public MV_ALL_MATCH_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_ALL_MATCH_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_ALL_MATCH_INFO implements Structure.ByValue {
		
	};
}
