package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"pData", "nDataLen", "nRes"})
public class MV_CC_INPUT_FRAME_INFO extends Structure {
	/**
	 * [IN]     \u56fe\u50cf\u6570\u636e\u6307\u9488<br>
	 * C type : unsigned char*
	 */
	public Pointer pData;
	/** [IN]     \u56fe\u50cf\u5927\u5c0f */
	public int nDataLen;
	/** C type : unsigned int[8] */
	public int[] nRes = new int[8];
	public MV_CC_INPUT_FRAME_INFO() {
		super();
	}
	/**
	 * @param pData [IN]     \u56fe\u50cf\u6570\u636e\u6307\u9488<br>
	 * C type : unsigned char*<br>
	 * @param nDataLen [IN]     \u56fe\u50cf\u5927\u5c0f<br>
	 * @param nRes C type : unsigned int[8]
	 */
	public MV_CC_INPUT_FRAME_INFO(Pointer pData, int nDataLen, int nRes[]) {
		super();
		this.pData = pData;
		this.nDataLen = nDataLen;
		if ((nRes.length != this.nRes.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.nRes = nRes;
	}
	public MV_CC_INPUT_FRAME_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_CC_INPUT_FRAME_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_CC_INPUT_FRAME_INFO implements Structure.ByValue {
		
	};
}
