package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({ "nDeviceNum", "pDeviceInfo"})
public class MV_CC_DEVICE_INFO_LIST extends Structure {
	/** ch:\u5728\u7ebf\u8bbe\u5907\u6570\u91cf | en:Online Device Number */
	public int nDeviceNum;
	/**
	 * ch:\u652f\u6301\u6700\u591a256\u4e2a\u8bbe\u5907 | en:Support up to 256 devices<br>
	 * C type : MV_CC_DEVICE_INFO*[256]
	 */
	public MV_CC_DEVICE_INFO.ByReference[] pDeviceInfo = new MV_CC_DEVICE_INFO.ByReference[256];
	public MV_CC_DEVICE_INFO_LIST() {
		super();
	}

	/**
	 * @param nDeviceNum ch:\u5728\u7ebf\u8bbe\u5907\u6570\u91cf | en:Online Device Number<br>
	 * @param pDeviceInfo ch:\u652f\u6301\u6700\u591a256\u4e2a\u8bbe\u5907 | en:Support up to 256 devices<br>
	 * C type : MV_CC_DEVICE_INFO*[256]
	 */
	public MV_CC_DEVICE_INFO_LIST(int nDeviceNum, MV_CC_DEVICE_INFO.ByReference pDeviceInfo[]) {
		super();
		this.nDeviceNum = nDeviceNum;
		if ((pDeviceInfo.length != this.pDeviceInfo.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.pDeviceInfo = pDeviceInfo;
	}
	public MV_CC_DEVICE_INFO_LIST(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_CC_DEVICE_INFO_LIST implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_CC_DEVICE_INFO_LIST implements Structure.ByValue {
		
	};
}
