package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nWidth", "nHeight", "enSrcPixelType", "pSrcData", "nSrcDataLen", "enDstPixelType", "pDstBuffer", "nDstLen", "nDstBufferSize", "nRes"})
public class MV_CC_PIXEL_CONVERT_PARAM extends Structure {
	/** [IN]     ch:\u56fe\u50cf\u5bbd | en:Width */
	public short nWidth;
	/** [IN]     ch:\u56fe\u50cf\u9ad8 | en:Height */
	public short nHeight;
	/**
	 * @see MvGvspPixelType<br>
	 * [IN]     ch:\u6e90\u50cf\u7d20\u683c\u5f0f | en:Source pixel format<br>
	 * C type : MvGvspPixelType
	 */
	public int enSrcPixelType;
	/**
	 * [IN]     ch:\u8f93\u5165\u6570\u636e\u7f13\u5b58 | en:Input data buffer<br>
	 * C type : unsigned char*
	 */
	public Pointer pSrcData;
	/** [IN]     ch:\u8f93\u5165\u6570\u636e\u5927\u5c0f | en:Input data size */
	public int nSrcDataLen;
	/**
	 * @see MvGvspPixelType<br>
	 * [IN]     ch:\u76ee\u6807\u50cf\u7d20\u683c\u5f0f | en:Destination pixel format<br>
	 * C type : MvGvspPixelType
	 */
	public int enDstPixelType;
	/**
	 * [OUT]    ch:\u8f93\u51fa\u6570\u636e\u7f13\u5b58 | en:Output data buffer<br>
	 * C type : unsigned char*
	 */
	public Pointer pDstBuffer;
	/** [OUT]    ch:\u8f93\u51fa\u6570\u636e\u5927\u5c0f | en:Output data size */
	public int nDstLen;
	/** [IN]     ch:\u63d0\u4f9b\u7684\u8f93\u51fa\u7f13\u51b2\u533a\u5927\u5c0f | en:Provided outbut buffer size */
	public int nDstBufferSize;
	/** C type : unsigned int[4] */
	public int[] nRes = new int[4];
	public MV_CC_PIXEL_CONVERT_PARAM() {
		super();
	}
	public MV_CC_PIXEL_CONVERT_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_CC_PIXEL_CONVERT_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_CC_PIXEL_CONVERT_PARAM implements Structure.ByValue {
		
	};
}
