package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"EventName", "nEventID", "nStreamChannel", "nBlockIdHigh", "nBlockIdLow", "nTimestampHigh", "nTimestampLow", "pEventData", "nEventDataSize", "nReserved"})
public class MV_EVENT_OUT_INFO extends Structure {
	/**
	 * Event\u540d\u79f0 | en:Event name<br>
	 * C type : char[128]
	 */
	public byte[] EventName = new byte[128];
	/** Event\u53f7 | en:Event ID */
	public short nEventID;
	/** \u6d41\u901a\u9053\u5e8f\u53f7 | en:Circulation number */
	public short nStreamChannel;
	/** \u5e27\u53f7\u9ad8\u4f4d | en:BlockId high */
	public int nBlockIdHigh;
	/** \u5e27\u53f7\u4f4e\u4f4d | en:BlockId low */
	public int nBlockIdLow;
	/** \u65f6\u95f4\u6233\u9ad8\u4f4d | en:Timestramp high */
	public int nTimestampHigh;
	/** \u65f6\u95f4\u6233\u4f4e\u4f4d | en:Timestramp low */
	public int nTimestampLow;
	/**
	 * Event\u6570\u636e | en:Event data<br>
	 * C type : void*
	 */
	public Pointer pEventData;
	/** Event\u6570\u636e\u957f\u5ea6 | en:Event data len */
	public int nEventDataSize;
	/**
	 * \u9884\u7559 | en:Reserved<br>
	 * C type : unsigned int[16]
	 */
	public int[] nReserved = new int[16];
	public MV_EVENT_OUT_INFO() {
		super();
	}
	public MV_EVENT_OUT_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_EVENT_OUT_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_EVENT_OUT_INFO implements Structure.ByValue {
		
	};
}
