package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"pBufAddr", "stFrameInfo", "nRes"})
public class MV_FRAME_OUT extends Structure {
	/**
	 * ch:\u56fe\u50cf\u6307\u9488\u5730\u5740 | en: pointer of image<br>
	 * C type : unsigned char*
	 */
	public Pointer pBufAddr;
	/**
	 * ch:\u56fe\u50cf\u4fe1\u606f | en:information of the specific image<br>
	 * C type : MV_FRAME_OUT_INFO_EX
	 */
	public MV_FRAME_OUT_INFO_EX stFrameInfo;
	/**
	 * ch:\u4fdd\u7559 | en:reserved<br>
	 * C type : unsigned int[16]
	 */
	public int[] nRes = new int[16];
	public MV_FRAME_OUT() {
		super();
	}
	/**
	 * @param pBufAddr ch:\u56fe\u50cf\u6307\u9488\u5730\u5740 | en: pointer of image<br>
	 * C type : unsigned char*<br>
	 * @param stFrameInfo ch:\u56fe\u50cf\u4fe1\u606f | en:information of the specific image<br>
	 * C type : MV_FRAME_OUT_INFO_EX<br>
	 * @param nRes ch:\u4fdd\u7559 | en:reserved<br>
	 * C type : unsigned int[16]
	 */
	public MV_FRAME_OUT(Pointer pBufAddr, MV_FRAME_OUT_INFO_EX stFrameInfo, int nRes[]) {
		super();
		this.pBufAddr = pBufAddr;
		this.stFrameInfo = stFrameInfo;
		if ((nRes.length != this.nRes.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.nRes = nRes;
	}
	public MV_FRAME_OUT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_FRAME_OUT implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_FRAME_OUT implements Structure.ByValue {
		
	};
}
