package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nWidth", "nHeight", "enPixelType", "nFrameNum", "nDevTimeStampHigh", "nDevTimeStampLow", "nReserved0", "nHostTimeStamp", "nFrameLen", "nLostPacket", "nReserved"})
public class MV_FRAME_OUT_INFO extends Structure {
	/** ch:\u56fe\u50cf\u5bbd | en:Image Width */
	public short nWidth;
	/** ch:\u56fe\u50cf\u9ad8 | en:Image Height */
	public short nHeight;
	/**
	 * @see MvGvspPixelType<br>
	 * ch:\u50cf\u7d20\u683c\u5f0f | en:Pixel Type<br>
	 * C type : MvGvspPixelType
	 */
	public int enPixelType;
	/** ch:\u5e27\u53f7 | en:Frame Number */
	public int nFrameNum;
	/** ch:\u65f6\u95f4\u6233\u9ad832\u4f4d | en:Timestamp high 32 bits */
	public int nDevTimeStampHigh;
	/** ch:\u65f6\u95f4\u6233\u4f4e32\u4f4d | en:Timestamp low 32 bits */
	public int nDevTimeStampLow;
	/** ch:\u4fdd\u7559\uff0c8\u5b57\u8282\u5bf9\u9f50 | en:Reserved, 8-byte aligned */
	public int nReserved0;
	/** ch:\u4e3b\u673a\u751f\u6210\u7684\u65f6\u95f4\u6233 | en:Host-generated timestamp */
	public long nHostTimeStamp;
	public int nFrameLen;
	/** \u672c\u5e27\u4e22\u5305\u6570 */
	public int nLostPacket;
	/** C type : unsigned int[2] */
	public int[] nReserved = new int[2];
	public MV_FRAME_OUT_INFO() {
		super();
	}
	public MV_FRAME_OUT_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_FRAME_OUT_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_FRAME_OUT_INFO implements Structure.ByValue {
		
	};
}
