package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nReviceDataSize", "nLostPacketCount", "nLostFrameCount", "nNetRecvFrameCount", "nRequestResendPacketCount", "nResendPacketCount"})
public class MV_MATCH_INFO_NET_DETECT extends Structure {
	/** ch:\u5df2\u63a5\u6536\u6570\u636e\u5927\u5c0f  [\u7edf\u8ba1StartGrabbing\u548cStopGrabbing\u4e4b\u95f4\u7684\u6570\u636e\u91cf] | en:Received data size */
	public long nReviceDataSize;
	/** ch:\u4e22\u5931\u7684\u5305\u6570\u91cf | en:Number of packets lost */
	public long nLostPacketCount;
	/** ch:\u4e22\u5e27\u6570\u91cf | en:Number of frames lost */
	public int nLostFrameCount;
	/** ch:\u4fdd\u7559 | en:Reserved */
	public int nNetRecvFrameCount;
	/** \u8bf7\u6c42\u91cd\u53d1\u5305\u6570 */
	public long nRequestResendPacketCount;
	/** \u91cd\u53d1\u5305\u6570 */
	public long nResendPacketCount;
	public MV_MATCH_INFO_NET_DETECT() {
		super();
	}
	/**
	 * @param nReviceDataSize ch:\u5df2\u63a5\u6536\u6570\u636e\u5927\u5c0f  [\u7edf\u8ba1StartGrabbing\u548cStopGrabbing\u4e4b\u95f4\u7684\u6570\u636e\u91cf] | en:Received data size<br>
	 * @param nLostPacketCount ch:\u4e22\u5931\u7684\u5305\u6570\u91cf | en:Number of packets lost<br>
	 * @param nLostFrameCount ch:\u4e22\u5e27\u6570\u91cf | en:Number of frames lost<br>
	 * @param nNetRecvFrameCount ch:\u4fdd\u7559 | en:Reserved<br>
	 * @param nRequestResendPacketCount \u8bf7\u6c42\u91cd\u53d1\u5305\u6570<br>
	 * @param nResendPacketCount \u91cd\u53d1\u5305\u6570
	 */
	public MV_MATCH_INFO_NET_DETECT(long nReviceDataSize, long nLostPacketCount, int nLostFrameCount, int nNetRecvFrameCount, long nRequestResendPacketCount, long nResendPacketCount) {
		super();
		this.nReviceDataSize = nReviceDataSize;
		this.nLostPacketCount = nLostPacketCount;
		this.nLostFrameCount = nLostFrameCount;
		this.nNetRecvFrameCount = nNetRecvFrameCount;
		this.nRequestResendPacketCount = nRequestResendPacketCount;
		this.nResendPacketCount = nResendPacketCount;
	}
	public MV_MATCH_INFO_NET_DETECT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_MATCH_INFO_NET_DETECT implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_MATCH_INFO_NET_DETECT implements Structure.ByValue {
		
	};
}
