package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"CrtlInEndPoint", "CrtlOutEndPoint", "StreamEndPoint", "EventEndPoint", "idVendor", "idProduct", "nDeviceNumber", "chDeviceGUID", "chVendorName", "chModelName", "chFamilyName", "chDeviceVersion", "chManufacturerName", "chSerialNumber", "chUserDefinedName", "nbcdUSB", "nReserved"})
public class MV_USB3_DEVICE_INFO extends Structure {
	/** ch:\u63a7\u5236\u8f93\u5165\u7aef\u70b9 | en:Control input endpoint */
	public byte CrtlInEndPoint;
	/** ch:\u63a7\u5236\u8f93\u51fa\u7aef\u70b9 | en:Control output endpoint */
	public byte CrtlOutEndPoint;
	/** ch:\u6d41\u7aef\u70b9 | en:Flow endpoint */
	public byte StreamEndPoint;
	/** ch:\u4e8b\u4ef6\u7aef\u70b9 | en:Event endpoint */
	public byte EventEndPoint;
	/** ch:\u4f9b\u5e94\u5546ID\u53f7 | en:Vendor ID Number */
	public short idVendor;
	/** ch:\u4ea7\u54c1ID\u53f7 | en:Device ID Number */
	public short idProduct;
	/** ch:\u8bbe\u5907\u5e8f\u5217\u53f7  | en:Device Serial Number */
	public int nDeviceNumber;
	/**
	 * ch:\u8bbe\u5907GUID\u53f7 | en:Device GUID Number<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chDeviceGUID = new byte[64];
	/**
	 * ch:\u4f9b\u5e94\u5546\u540d\u5b57 | en:Vendor Name<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chVendorName = new byte[64];
	/**
	 * ch:\u578b\u53f7\u540d\u5b57 | en:Model Name<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chModelName = new byte[64];
	/**
	 * ch:\u5bb6\u65cf\u540d\u5b57 | en:Family Name<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chFamilyName = new byte[64];
	/**
	 * ch:\u8bbe\u5907\u7248\u672c\u53f7 | en:Device Version<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chDeviceVersion = new byte[64];
	/**
	 * ch:\u5236\u9020\u5546\u540d\u5b57 | en:Manufacturer Name<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chManufacturerName = new byte[64];
	/**
	 * ch:\u5e8f\u5217\u53f7 | en:Serial Number<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chSerialNumber = new byte[64];
	/**
	 * ch:\u7528\u6237\u81ea\u5b9a\u4e49\u540d\u5b57 | en:User Defined Name<br>
	 * C type : unsigned char[64]
	 */
	public byte[] chUserDefinedName = new byte[64];
	/** ch:\u652f\u6301\u7684USB\u534f\u8bae | en:Support USB Protocol */
	public int nbcdUSB;
	/**
	 * ch:\u4fdd\u7559\u5b57\u8282 | en:Reserved bytes<br>
	 * C type : unsigned int[3]
	 */
	public int[] nReserved = new int[3];
	public MV_USB3_DEVICE_INFO() {
		super();
	}
	public MV_USB3_DEVICE_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MV_USB3_DEVICE_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends MV_USB3_DEVICE_INFO implements Structure.ByValue {
		
	};
}
