package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nCurValue", "nMax", "nMin", "nInc", "nReserved"})
public class MVCC_INTVALUE extends Structure {
	/** ch:\u5f53\u524d\u503c | en:Current Value */
	public int nCurValue;
	public int nMax;
	public int nMin;
	public int nInc;
	/** C type : unsigned int[4] */
	public int[] nReserved = new int[4];
	public MVCC_INTVALUE() {
		super();
	}
	/**
	 * @param nCurValue ch:\u5f53\u524d\u503c | en:Current Value<br>
	 * @param nReserved C type : unsigned int[4]
	 */
	public MVCC_INTVALUE(int nCurValue, int nMax, int nMin, int nInc, int nReserved[]) {
		super();
		this.nCurValue = nCurValue;
		this.nMax = nMax;
		this.nMin = nMin;
		this.nInc = nInc;
		if ((nReserved.length != this.nReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.nReserved = nReserved;
	}
	public MVCC_INTVALUE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MVCC_INTVALUE implements Structure.ByReference {
		
	};
	public static class ByValue extends MVCC_INTVALUE implements Structure.ByValue {
		
	};
}
