package com.happen23.agv.hik_camera.lib_hik;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : include\CameraParams.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
@Structure.FieldOrder({"nCurValue", "nSupportedNum", "nSupportValue", "nReserved"})
public class MVCC_ENUMVALUE extends Structure {
	/** ch:\u5f53\u524d\u503c | en:Current Value */
	public int nCurValue;
	/** ch:\u6570\u636e\u7684\u6709\u6548\u6570\u636e\u4e2a\u6570 | en:Number of valid data */
	public int nSupportedNum;
	/** C type : unsigned int[64] */
	public int[] nSupportValue = new int[64];
	/** C type : unsigned int[4] */
	public int[] nReserved = new int[4];
	public MVCC_ENUMVALUE() {
		super();
	}
	/**
	 * @param nCurValue ch:\u5f53\u524d\u503c | en:Current Value<br>
	 * @param nSupportedNum ch:\u6570\u636e\u7684\u6709\u6548\u6570\u636e\u4e2a\u6570 | en:Number of valid data<br>
	 * @param nSupportValue C type : unsigned int[64]<br>
	 * @param nReserved C type : unsigned int[4]
	 */
	public MVCC_ENUMVALUE(int nCurValue, int nSupportedNum, int nSupportValue[], int nReserved[]) {
		super();
		this.nCurValue = nCurValue;
		this.nSupportedNum = nSupportedNum;
		if ((nSupportValue.length != this.nSupportValue.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.nSupportValue = nSupportValue;
		if ((nReserved.length != this.nReserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.nReserved = nReserved;
	}
	public MVCC_ENUMVALUE(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends MVCC_ENUMVALUE implements Structure.ByReference {
		
	};
	public static class ByValue extends MVCC_ENUMVALUE implements Structure.ByValue {
		
	};
}
